[project]
name = "streamlit-dividend-dashboard"
version = "0.1.0"
description = "A Streamlit application for visualizing and analyzing stock dividend data."
authors = [
    {name = "s"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "streamlit (>=1.44.1,<2.0.0)",
    "plotly (>=6.0.1,<7.0.0)",
    "streamlit-elements (>=0.1.0,<0.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
